version: '3.8'

services:
  web:
    build: .
    command: gunicorn dar_market.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8000:8000"
    environment:
      - DEBUG=0
      - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1,[::1]

volumes:
  static_volume:
  media_volume: 